# Site settings
title: Jack Johns
name: Jack Johns

# Build settings
markdown: kramdown

#Navbar links
primarylinks:
 - title: GitHub
   url: https://github.com/Jack-Johns
 - title: LinkedIn
   url: https://www.linkedin.com/in/jack-johns-183100177/
 - title: Email
   url: mailto:jack.johns@bt.com

#Skills to highlight
skills:
 - Java
 - C#
 - Python
 - SQL
 - HTML
 - CSS
 - Javascript
 - Android Development
 - Unity
 - VR/AR Development
 - Machine Learning
 - Deep Learning
 - IoT
 - Agile/SCRUM
 - Project Management

#Work experience is required
roles:
 - title: Applied Research Apprentice
   start: 2018
   end: Ongoing
   employer: BT Plc
   description: Working within a range of different research teams, inlcuding Security Futures, Operational Transformations, AI and Data Science and Internet of Things whilst completing my degree. <strong>Referee</strong> <a href="mailto:andrew.corston@bt.com">Andrew Corston</a> 
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2022
   subject: Digital and Technology Solutions - Data Analysis
   school: University of Exeter

#General intro at the top of the page
intro: |
  I am a keen technologist and software developer that loves thinking of innovative solutions to both company-specific and industry-wide problems. Machine learning is a passion of mine, finding new and useful ways to utilise it is something I am specifically interested in. I achieve results through using my technical knowledge, logical thinking and problem solving skills. <br><br>
  By working on various research projects, I have become proficient with computing languages such as Python (in the field of machine learning and robotics), Java (for both web development and Android applications) and C# (to develop applications in VR/AR). I also have experience in database creation, querying and management mostly through SQL.<br><br>
  I have also assumed the role of project manager on a few occasions, most notably on an application delivery project for BT's Emergency Response Team. This first hand experience of Agile leading will benefit me for future projects.
  

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Cloud Security</strong>: I partook in a 6 month project for the Security Futures team, in which my work was centred around building a PoC (Proof of Concept) that showed how to protect both PCs and internet of things (IoT) devices simultaneously from malicious domains and known security vulnerabilities using the existing architecture that BT has.<br/><br/>
   <strong>AR in Field Force</strong>: The 7 month project I completed in the Operational Transformations team consisted of a PoC that shows how live feeds of data can be displayed to an augmented reality wearable like the Microsoft HoloLens and how helpful that would be to the user. It demonstrated how our field force engineers could benefit from the use of wearables and how the data could be delivered to them through this process.<br/><br/>
   <strong>BERT for Chatbots</strong>: This 6 month project investigated a new Natural Language Processing (NLP) model called <a href="https://arxiv.org/abs/1810.04805">BERT</a>. I created and trained my own version of the model based on the standards and created a demo that showed the capabilities of it in a Question-Answering (QA) domain.<br/><br/>
   <strong>IoT for Assisted Living</strong>: I worked with <a href="http://consequentialrobotics.com/miroe">MiRo</a>, a robotic dog that hosts various IoT sensors and can be interacted with in different ways. Using MiRo, I created a demo based around assisted living, in which the robot uses it's microphones to detect specific keywords and retrieve data that would be useful, such as temperature or air quality data. <br/><br/>
   <strong>Emergency Response Team Companion Application</strong>: I led a team of fellow researchers as project manager on a project to improve BT's Emergency Response Team's current logging systems. We developed a web application that allows operatives to submit and view logs, all whilst in the field.​ This in turn will make the ERT more efficient at responding to incidents and in some cases, help save lives.​<br/><br/>
   <strong>Other Responsibilities and Achievements</strong>:<br/> <a href="https://theitpblog.wordpress.com/2020/01/23/5-mins-with-jack-johns-winner-of-the-christopher-mills-award-2019/">ITP Christopher Mills Award 2019 Winner</a> - An award that recognises individuals based on their use of science, maths or engineering within their Telecommunications based role. I was lucky enough to be given this award for the work I had produced in the first year of my apprenticeship.<br/><br/>
   Challenge Cup 2019 - There is a BT internal competition called the Challenge Cup in which teams plan and execute a project that would add benefit to the company. The Emergency Response Team application project was entered and I assumed the role of team captain. We made it to the semi-finals of the challenge cup, the top 50 teams in the UK and India out of over 3000 teams who originally entered.​<br/><br/>
   Recruitment - I held the role of Apprentice Attraction Ambassador for a number of years, starting from the beginning of my apprenticeship. My role was to inspire students to pursue a career in technology, specifically through an apprenticeship at BT. Responsibilities include: engaging with schools and event organisers, organising presence at an event, managing collateral, finding and training volunteers and mostly attending them myself.